# Generated by Django 4.1.7 on 2023-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('econtact', models.CharField(max_length=50)),
                ('eemail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
